/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enventrysystem;

/**
 *
 * @author dell
 */
import java.sql.*;
import java.util.Vector;
public class PurchaseForm extends javax.swing.JFrame {
Vector City=null;
Vector id =null;
Vector p_id=null;
Vector pprice=null;
int cindx;
int pindx;
Connection con1=null;
    
    void getData()
    {
       City=new Vector();
       id=new Vector();
       p_id=new Vector();
       pprice=new Vector();
       try
       {
        con1=initconnection.getConn();
       Statement stm=con1.createStatement();
       ResultSet rs=stm.executeQuery("select id,Cname,City from customerform");
       while(rs.next())
       {
       id.add(rs.getInt(1));
        c_id.addItem(rs.getString(2));
        City.add(rs.getString(3));
       }
        ResultSet rs1=stm.executeQuery("select p_id,pname,pprice from product");
       while(rs1.next())
       {
        p_id.add(rs1.getInt(1));
        pid.addItem(rs1.getString(2));
        pprice.add(rs1.getInt(3));
       }
       }catch(Exception tt)
       {}
       
    }
    public PurchaseForm() {
        initComponents();
          getData();
        setSize(600,600);
      
    }

    /**
     * This method is called fro m within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inv = new javax.swing.JTextField();
        c_id = new javax.swing.JComboBox<>();
        pid = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        home = new javax.swing.JButton();
        city = new javax.swing.JTextField();
        prprice = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(inv);
        inv.setBounds(110, 30, 130, 40);

        c_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier Name" }));
        c_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_idActionPerformed(evt);
            }
        });
        getContentPane().add(c_id);
        c_id.setBounds(20, 90, 130, 40);

        pid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product Item", " " }));
        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        getContentPane().add(pid);
        pid.setBounds(20, 150, 130, 40);

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(200, 310, 80, 30);

        home.setText("home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(470, 50, 72, 23);

        city.setText("city");
        getContentPane().add(city);
        city.setBounds(160, 90, 110, 40);

        prprice.setText("pprice");
        getContentPane().add(prprice);
        prprice.setBounds(160, 150, 110, 30);

        total.setText("total");
        getContentPane().add(total);
        total.setBounds(160, 200, 110, 30);

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        getContentPane().add(qty);
        qty.setBounds(70, 200, 70, 30);

        jLabel1.setText("Qty");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 210, 37, 16);

        jLabel2.setText("Invoice No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       try{
       String inv1=inv.getText();
       if(cindx!=0)
       {
       int custid=(Integer)id.get(cindx-2);
       int prid=(Integer)p_id.get(pindx-2);
       int ppric=Integer.parseInt(prprice.getText());
       int qty1=Integer.parseInt(qty.getText());
       int tot=Integer.parseInt(total.getText());
      PreparedStatement  ps=con1.prepareStatement("insert into purchase1(invoice_no,cid,prid,pprice,qty,total)values(?,?,?,?,?,?)");
      ps.setString(1, inv1);
      ps.setInt(2, custid);
      ps.setInt(3, prid);
      ps.setInt(4, ppric);
      ps.setInt(5, qty1);
      ps.setInt(6, tot);
      ps.executeUpdate();
        }
       }catch(Exception ee)
       {
       System.out.println(ee);
       }
    }//GEN-LAST:event_saveActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EnventryForm.main(new String[2]);
    }//GEN-LAST:event_homeActionPerformed

    private void c_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_idActionPerformed
        // TODO add your handling code here:
        cindx= c_id.getSelectedIndex();
        if(cindx!=0)
        {
          String s1=(String)City.get(cindx-2);
          city.setText(s1);
        }
    }//GEN-LAST:event_c_idActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
          pindx= pid.getSelectedIndex();
        if(pindx!=0)
        {
            Integer s1=(Integer)pprice.get(pindx-2);
          prprice.setText(s1+"");
        }
             
    }//GEN-LAST:event_pidActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
        int p=Integer.parseInt(prprice.getText());
        int qt=Integer.parseInt(qty.getText());
        total.setText((p*qt)+"");
    }//GEN-LAST:event_qtyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c_id;
    private javax.swing.JTextField city;
    private javax.swing.JButton home;
    private javax.swing.JTextField inv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> pid;
    private javax.swing.JTextField prprice;
    private javax.swing.JTextField qty;
    private javax.swing.JButton save;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
