/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enventrysystem;

/**
 *
 * @author dell
 */
import java.sql.*;
import java.util.*;
public class SalesForm extends javax.swing.JFrame {

   Vector City=null;
Vector id =null;
Vector p_id=null;
Vector sprice=null;
int cindx;
int pindx;
Connection con1=null;
 void getData()
    {
       City=new Vector();
       id=new Vector();
       p_id=new Vector();
       sprice=new Vector();
       try
       {
        con1=initconnection.getConn();
       Statement stm=con1.createStatement();
       ResultSet rs=stm.executeQuery("select cid,cname,ccity from customer_t");
       while(rs.next())
       {
       id.add(rs.getInt(1));
        c_id1.addItem(rs.getString(2));
        City.add(rs.getString(3));
       }
        ResultSet rs1=stm.executeQuery("select p_id,pname,pprice from product");
       while(rs1.next())
       {
        p_id.add(rs1.getInt(1));
        pid1.addItem(rs1.getString(2));
        sprice.add(rs1.getInt(3));
       }
       }catch(Exception tt)
       {}
       
    }
    public SalesForm() {
        initComponents();
         getData();
        setSize(600,600);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inv2 = new javax.swing.JTextField();
        c_id1 = new javax.swing.JComboBox<>();
        pid1 = new javax.swing.JComboBox<>();
        city1 = new javax.swing.JTextField();
        sprice1 = new javax.swing.JTextField();
        qty2 = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(inv2);
        inv2.setBounds(120, 20, 150, 40);

        c_id1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Custumer name" }));
        c_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_id1ActionPerformed(evt);
            }
        });
        getContentPane().add(c_id1);
        c_id1.setBounds(20, 80, 150, 40);

        pid1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product item" }));
        pid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pid1ActionPerformed(evt);
            }
        });
        getContentPane().add(pid1);
        pid1.setBounds(20, 140, 150, 40);

        city1.setText("City");
        getContentPane().add(city1);
        city1.setBounds(180, 80, 100, 30);

        sprice1.setText("sprice");
        getContentPane().add(sprice1);
        sprice1.setBounds(180, 140, 100, 30);

        qty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty2ActionPerformed(evt);
            }
        });
        getContentPane().add(qty2);
        qty2.setBounds(50, 190, 90, 30);

        total.setText("total");
        getContentPane().add(total);
        total.setBounds(180, 190, 100, 30);

        home.setText("home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(510, 40, 80, 30);

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(240, 270, 90, 40);

        jLabel1.setText("Invoice No");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 80, 30);

        jLabel2.setText("Qty");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 200, 19, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EnventryForm.main(new String[2]);
    }//GEN-LAST:event_homeActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
         try{
       String inv1=inv2.getText();
       if(cindx!=0)
       {
       int custid=(Integer)id.get(cindx-1);
       int prid=(Integer)p_id.get(pindx-1);
       int spric=Integer.parseInt(sprice1.getText());
       int qty1=Integer.parseInt(qty2.getText());
       int tot=Integer.parseInt(total.getText());
      PreparedStatement  ps=con1.prepareStatement("insert into selstable1(invoice_no,cid,prid,sprice,qty,total)values(?,?,?,?,?,?)");
      ps.setString(1, inv1);
      ps.setInt(2, custid);
      ps.setInt(3, prid);
      ps.setInt(4, spric);
      ps.setInt(5, qty1);
      ps.setInt(6, tot);
      ps.executeUpdate();
        }
       }catch(Exception ee)
       {
       System.out.println(ee);
       }
                                        

    }//GEN-LAST:event_saveActionPerformed

    private void c_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_id1ActionPerformed
        // TODO add your handling code here:
        cindx= c_id1.getSelectedIndex();
        if(cindx!=0)
        {
          String s1=(String)City.get(cindx-1);
          city1.setText(s1);
        }
    }//GEN-LAST:event_c_id1ActionPerformed

    private void pid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pid1ActionPerformed
         pindx= pid1.getSelectedIndex();
        if(pindx!=0)
        {  
            Integer s1=(Integer)sprice.get(pindx-1);
          sprice1.setText(s1+"");
        }
    }//GEN-LAST:event_pid1ActionPerformed

    private void qty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty2ActionPerformed
    int p=Integer.parseInt(sprice1.getText());
        int qt=Integer.parseInt(qty2.getText());
        total.setText((p*qt)+"");
    }//GEN-LAST:event_qty2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesForm().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c_id1;
    private javax.swing.JTextField city1;
    private javax.swing.JButton home;
    private javax.swing.JTextField inv2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> pid1;
    private javax.swing.JTextField qty2;
    private javax.swing.JButton save;
    private javax.swing.JTextField sprice1;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
