/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enventrysystem;

/**
 *
 * @author dell
 */
import java.sql.*;  
import java.util.Vector;
public class SalesReturn extends javax.swing.JFrame {

    Vector City=null;
Vector id =null;
Vector p_id=null;
Vector pprice=null;
int cindx;
int pindx;
Connection con1=null;
    void getData()
    {
        City=new Vector();
       id=new Vector();
     p_id=new Vector();
       pprice=new Vector();
       try
       {
        con1=initconnection.getConn();
       Statement stm=con1.createStatement();
       ResultSet rs=stm.executeQuery("select cid,cname,ccity from customer_t");
       while(rs.next())
       {
       id.add(rs.getInt(1));
        customer.addItem(rs.getString(2));
        City.add(rs.getString(3));
       }
       ResultSet rs1=stm.executeQuery("select p_id,pname,pprice from product");
       while(rs1.next())
       {
        p_id.add(rs1.getInt(1));
        product.addItem(rs1.getString(2));
        pprice.add(rs1.getInt(3));
       }
       }catch(Exception tt)
       {}
    }
    public SalesReturn() {
        initComponents();
         getData();
        setSize(600,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customer = new javax.swing.JComboBox<>();
        product = new javax.swing.JComboBox<>();
        sqty = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        sprice = new javax.swing.JTextField();
        scity = new javax.swing.JTextField();
        reason = new javax.swing.JTextField();
        home = new javax.swing.JToggleButton();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        customer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer Name" }));
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        getContentPane().add(customer);
        customer.setBounds(50, 30, 230, 50);

        product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product item" }));
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });
        getContentPane().add(product);
        product.setBounds(50, 100, 230, 50);

        sqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqtyActionPerformed(evt);
            }
        });
        getContentPane().add(sqty);
        sqty.setBounds(70, 180, 90, 30);

        total.setText("Total");
        getContentPane().add(total);
        total.setBounds(190, 180, 90, 30);

        sprice.setText("Sprice");
        getContentPane().add(sprice);
        sprice.setBounds(290, 100, 110, 50);

        scity.setText("City");
        getContentPane().add(scity);
        scity.setBounds(300, 30, 110, 50);
        getContentPane().add(reason);
        reason.setBounds(100, 230, 180, 40);

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(220, 300, 90, 30);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(120, 300, 90, 30);

        jLabel1.setText("Reason");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 240, 70, 20);

        jLabel2.setText("Qty");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 190, 37, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        EnventryForm.main(new String[2]);
    }//GEN-LAST:event_homeActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
         try{
       
       if(cindx!=0)
       {
           int custid=(Integer)id.get(cindx-1);
            int prid=(Integer)p_id.get(pindx-1);
       
       int qty1=Integer.parseInt(sqty.getText());
       int tot=Integer.parseInt(total.getText());
       String reason1=reason.getText();
      PreparedStatement  ps=con1.prepareStatement
        ("insert into sales_return(pro_id,qty,reason,total,cus_id)values(?,?,?,?,?)");
     
      ps.setInt(1, prid);
      ps.setInt(2, qty1);
      ps.setString(3, reason1);
      
      ps.setInt(4, tot);
       ps.setInt(5, custid);
      ps.executeUpdate();
        }
       }catch(Exception ee)
       {
       System.out.println(ee);
       }
       
    }//GEN-LAST:event_submitActionPerformed

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        // TODO add your handling code here:
         pindx= product.getSelectedIndex();
        if(pindx!=0)
        {
            Integer s1=(Integer)pprice.get(pindx-1);
          sprice.setText(s1+"");
        }
    }//GEN-LAST:event_productActionPerformed

    private void sqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqtyActionPerformed
        // TODO add your handling code here:
         int p=Integer.parseInt(sprice.getText());
        int qt=Integer.parseInt(sqty.getText());
        total.setText((p*qt)+"");
    }//GEN-LAST:event_sqtyActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
        cindx= customer.getSelectedIndex();
        if(cindx!=0)
        {
          String s1=(String)City.get(cindx-1);
          scity.setText(s1);
        }
    }//GEN-LAST:event_customerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> customer;
    private javax.swing.JToggleButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> product;
    private javax.swing.JTextField reason;
    private javax.swing.JTextField scity;
    private javax.swing.JTextField sprice;
    private javax.swing.JTextField sqty;
    private javax.swing.JButton submit;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
